directories:
  dataset_dir:
    classification: 
      - /data/cnn/datasets
    object_detection: 
      - /data/object_detection/datasets
    semantic_segmentation: 
      - /data/object_detection/datasets
      - /data/segmentation/datasets
  weight_dir:
    classification: /data/cnn/params
    object_detection: /data/object_detection/params
    semantic_segmentation: /data/segmentation/params
  evaluation_result:
    classification: /data/cnn/evals
    object_detection: /data/object_detection/evals
    semantic_segmentation: /data/segmentation/evals