version: '3'
services:
  # Container for evaluating and selecting models
  model_selection:
    container_name: ${ANALYSIS_HOST}
    image: pytorch_analysis # Specify the image name
    build:
      context: $PWD/analysis
      shm_size: '8gb'  # Increase shared memory size for NN Training
      dockerfile: Dockerfile
      args:
        - USRPASSWD=${ANALYSIS_USRPASSWD}
    environment:
      - PYTHONPATH=/repos/YOLOX # Avoid NoduleNotFoundError of YOLOX (https://github.com/Megvii-BaseDetection/YOLOX/issues/154) 
    volumes:
      # Share the volumes between external folder and internal container
      - $PWD/analysis/scripts:/scripts  # Analysis scripts
    ports:
      # Expose a port for external access
      - 80:6006  # Tensorboard
    # -i option
    stdin_open: true
    # -t option
    tty: true
    # gpu support
    runtime: nvidia
    # Increase shared memory size for NN Training (https://github.com/pytorch/pytorch/issues/5040)
    shm_size: '8gb'
    # Startup command
    command:
      bash
  # Container for a web app showing annotation data
  #display_app:
