directories:
  dataset_dir:
    classification: 
      - /app/datasets/classification
    object_detection: 
      - /app/datasets/object_detection
    semantic_segmentation: 
      - /app/datasets/object_detection
      - /app/datasets/segmentation
  weight_dir:
    classification: /app/params/classification
    object_detection: /app/params/object_detection
    semantic_segmentation: /app/params/segmentation
  database_dir: /app/db

class_names:
  voc: idx_to_class.yml

database:
  table_name:
    eval_result:
      classification: classification
      object_detection: detection
      semantic_segmentation: segmentation

models:
  default_load_weights:
    classification: 
    object_detection: 
    semantic_segmentation:
      - vocseg_fcn_resnet50.prm
      - vocseg_deeplabv3_resnet50.prm
      - coco_lraspp_mobilenetv3.prm

display:
  records_per_table: 200