directories:
  dataset_dir:
    classification: 
      - /app/datasets/classification
    object_detection: 
      - /app/datasets/object_detection
    semantic_segmentation: 
      - /app/datasets/object_detection
      - /app/datasets/segmentation
  weight_dir:
    classification: /app/params/classification
    object_detection: /app/params/object_detection
    semantic_segmentation: /app/params/segmentation
  database_dir: /app/db

database:
  table_name:
    eval_result:
      classification: classification
      object_detection: detection
      semantic_segmentation: segmentation

models:
  default_load_weights:
    classification: 
    object_detection: 
    semantic_segmentation:
      - vocsegmentation_fcn.prm
      - vocsegmentation_deeplabv3.prm
      - coco_lraspp.prm

display:
  records_per_table: 200